-- Table des notes
create table notes (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table des enregistrements
create table recordings (
  id bigint generated by default as identity primary key,
  title text not null,
  audio_url text not null,
  duration text not null,
  date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Fonction pour mettre à jour le timestamp updated_at
create or replace function handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Trigger pour les notes
create trigger handle_notes_updated_at
  before update on notes
  for each row
  execute function handle_updated_at();

-- Trigger pour les enregistrements
create trigger handle_recordings_updated_at
  before update on recordings
  for each row
  execute function handle_updated_at();

-- Politique RLS pour les notes
create policy "Accès public aux notes"
  on notes
  for all
  using (true)
  with check (true);

-- Politique RLS pour les enregistrements
create policy "Accès public aux enregistrements"
  on recordings
  for all
  using (true)
  with check (true);

-- Activer RLS sur les tables
alter table notes enable row level security;
alter table recordings enable row level security;
